# Generated by Django 6.1.1 on 2026-09-06 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Corpus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('target', 'Target - the domain you want vocabulary for'), ('control', 'Control - general language to compare against')], default='target', max_length=16)),
                ('language', models.CharField(default='tr', help_text="ISO code. 'tr' or 'az' enable Turkish dotted/dotless i handling.", max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysed_at', models.DateTimeField(blank=True, null=True)),
                ('control_corpus', models.ForeignKey(blank=True, help_text="Control corpus to score this one's n-grams against.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scored_targets', to='corpus.corpus')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corpora', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'corpora',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=500)),
                ('text', models.TextField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('corpus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='corpus.corpus')),
            ],
            options={
                'ordering': ['filename'],
            },
        ),
        migrations.CreateModel(
            name='Ngram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.PositiveSmallIntegerField()),
                ('key', models.CharField(max_length=500)),
                ('display', models.CharField(max_length=500)),
                ('count', models.PositiveIntegerField()),
                ('importance', models.FloatField(blank=True, null=True)),
                ('selected', models.BooleanField(default=False)),
                ('chosen_text', models.TextField(blank=True, default='')),
                ('corpus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ngrams', to='corpus.corpus')),
            ],
            options={
                'ordering': ['-count'],
            },
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('folded_text', models.TextField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentences', to='corpus.document')),
            ],
        ),
        migrations.AddConstraint(
            model_name='corpus',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_corpus_name_per_owner'),
        ),
        migrations.AddIndex(
            model_name='ngram',
            index=models.Index(fields=['corpus', 'n', '-count'], name='corpus_ngra_corpus__990639_idx'),
        ),
        migrations.AddIndex(
            model_name='ngram',
            index=models.Index(fields=['corpus', 'selected'], name='corpus_ngra_corpus__ff93f7_idx'),
        ),
        migrations.AddConstraint(
            model_name='ngram',
            constraint=models.UniqueConstraint(fields=('corpus', 'n', 'key'), name='unique_ngram_per_corpus'),
        ),
        migrations.AddIndex(
            model_name='sentence',
            index=models.Index(fields=['document'], name='corpus_sent_documen_5074b6_idx'),
        ),
    ]
